# Generated by Django 3.1.10 on 2021-05-10 06:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210510_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(default='FTPECSISSRA9UV12', max_length=16, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='code',
            field=models.CharField(default='LYXBR2U2JUIPAPZ1', max_length=16, unique=True, verbose_name='Code'),
        ),
    ]
