# Generated by Django 3.1.10 on 2021-05-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210510_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(default='FT8F14VYTX3M444N', max_length=16, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='code',
            field=models.CharField(default='LY6L5ACOY99WNIKI', max_length=16, unique=True, verbose_name='Code'),
        ),
    ]
