# Generated by Django 3.1.10 on 2021-05-10 07:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210510_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='collection',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(default='FTKH7SFS8OCT96RS', max_length=16, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='code',
            field=models.CharField(default='LY3BF25T4CPZ778F', max_length=16, unique=True, verbose_name='Code'),
        ),
    ]
