# Generated by Django 3.1.10 on 2021-05-10 07:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210510_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='collection',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(default='FTLCDCXG7T70A9H2', max_length=16, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='code',
            field=models.CharField(default='LY2I5X1CMDSTNSM8', max_length=16, unique=True, verbose_name='Code'),
        ),
    ]
