# Generated by Django 3.1.10 on 2021-05-10 07:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210510_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='collection',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(default='FTXZ8MW4CWC031HD', max_length=16, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='code',
            field=models.CharField(default='LYQFFAPA35FS6NQ5', max_length=16, unique=True, verbose_name='Code'),
        ),
    ]
