# Generated by Django 4.0.6 on 2022-07-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210513_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='code',
            field=models.CharField(default='FTDJ4GNGFSHJTN5C', max_length=16, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='floodplain',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='layer',
            name='code',
            field=models.CharField(default='LYEUDBNWVLGBN8AM', max_length=16, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
